server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vote_system_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置mapper路径
  config-location: classpath:mybatis-config.xml # 配置配置文件路径